#!/usr/bin/env bash
# configures a server to listen on port 80 of all the server’s active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo /etc/init.d/nginx restart
sudo rm /var/run/nginx.pid
